.\" Copyright (c) 2003, Sergei Kolobov
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id$
.\"
.Dd July 26, 2003
.Dt PR-NEW 1
.Os
.Sh NAME
.Nm pr-new
.Nd submit PR with a new FreeBSD port
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl m Ar mode
.Op Fl s Ar severity
.Op Fl p Ar priority
.Sh DESCRIPTION
.Nm
simplifies submitting a Problem Report (PR) 
with a new FreeBSD port.
It automatically fills in some fields in the 
.Xr send-pr 1
form,
generates a shar file containing the port, 
names the file according to the port name and version,
runs 
.Xr send-pr 1
to actually submit PR and then 
optionally saves the shar file for archiving purposes.
.Pp
The options are as follows:
.Bl -tag -width ".Fl s Ar severity"
.It Fl h
Display usage for
.Nm .
.It Fl m Ar mode
Select operation mode.
Valid values for 
.Ar mode 
are:
.Bl -tag -width update
.It Ar new
PR for submitting a new port.
This is the default if invoked as
.Xr pr-new 1 .
.It Ar change
PR for changing (but not updating) an existing port.
This is the default if invoked as
.Xr pr-change 1 .
.It Ar update
PR for updating an existing port to a newer version.
This is the default if invoked as
.Xr pr-update 1 .
.El
.It Fl s Ar severity
Sets severity of the PR.
Valid values for 
.Ar severity 
are:
.Em non-critical ,
.Em serious ,
.Em critical .
Default is 
.Em non-critical .
.It Fl p Ar priority
Sets priority of the PR.
Valid values for 
.Ar priority 
are:
.Em low ,
.Em medium ,
.Em high .
Default is 
.Em low .
.El
.Pp
Run 
.Nm
from a directory containing the new port.
First,
.Nm
runs
.Xr portlint 1
to verify the port files for correctness,
then generates a shar file.
.Sh ENVIRONMENT
The
.Nm
command uses the following environment variables,
normally set through the 
.Pa ~/.porttools
configuration file:
.Bl -tag -width ORGANIZATION
.It Ev EMAIL
Your e-mail address to use in From: field of the PR form.
.It Ev FULLNAME
Your full name in From: and Originator fields of the PR form.
.It Ev ORGANIZATION
Name of your organization (if any) to use in the PR form.
.It Ev ARCHIVE_DIR
Directory to archive sent diff and shar files.
.El
.Sh FILES
.Bl -tag -width ".Pa ~/.porttools" -compact
.It Pa ~/.porttools
FreeBSD Port Tools configuration file.
It is generated automatically if missing.
.El
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr portlint 1 ,
.Xr pr-change 1 ,
.Xr pr-new 1 ,
.Xr testport 1
.Sh HISTORY
The
.Nm
manual page example first appeared in FreeBSD Port Tools 0.20.
.Sh AUTHORS
This manual page was written by
.An Sergei Kolobov Aq sergei@kolobov.com .
.Sh BUGS
Please report any bugs to the author.
