#!/bin/sh
#
# FreeBSD Port Tools __VERSION__
#
# pr-update, pr-change, pr-new
# Scripts to simplify submitting a FreeBSD Problem Report (PR)
# for updated, changed, or new port
#
# Copyright (c) 2003, Sergei Kolobov
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id$
#

# Port Tools configuration file
CONFIG="${HOME}/.porttools"

# Commands to output a message with standard prefix
MSG='echo ===> '
ERROR='echo Error '

# Usage
usage ()
{
cat << EOF
FreeBSD Port Tools __VERSION__
Usage: $0 [-h] [-m <mode>] [-d <diff mode>] [-s <severity>] [-p <priority>]
	-h	- Display this usage
	-m <mode> - Select mode of operation:
		new - submitting new port
		change - changing a port 
		update - updating a port to newer version
	-d <diff mode> - Select diff generation mode:
		CVS - against CVS
		<dir> - against Ports tree in <dir>
		<pattern> - against original port in <pwd><pattern>
	-s <severity> - Set PR's severity to <severity>
	-p <priority> - Set PR's priority to <priority>
EOF
}


# Initialize arguments to the default values
MODE="`basename $0 | sed 's/pr-//'`"
SEVERITY="non-critical"
PRIORITY="low"

# Parse command line arguments
ARGS=`/usr/bin/getopt hm:d:s:p: $*`
if [ $? != 0 ]
then
	echo "Error: invalid arguments"
	usage
	exit 2
fi

set -- $ARGS
for i 
do
	case "$i" in
	-h)	# help
		usage
		exit 0
		;;
	-m)	# mode
		MODE=$2
		case "${MODE}" in
		new|change|update)
			shift
			shift
			;;
		*)
			echo "Error: invalid mode: ${MODE}"
			echo "Valid values: new, change, update"
			exit 2
			;;
		esac
		;;
	-d)	# diff mode
		DIFF_MODE=$2
		shift
		shift
		;;
	-s)	# severity
		SEVERITY=$2
		case "${SEVERITY}" in
		non-critical|serious|critical)
			shift
			shift
			;;
		*)
			echo "Error: invalid severity: ${SEVERITY}"
			echo "Valid values: non-critical, serious, critical"
			exit 2
			;;
		esac
		;;
	-p)	# prority
		PRIORITY=$2
		case "${PRIORITY}" in
		low|medium|high)
			shift
			shift
			;;
		*)
			echo "Error: invalid priority: ${PRIORITY}"
			echo "Valid values: low, medium, high"
			exit 2
			;;
		esac
		;;
	esac
done

# Run portlint(1) to validate port's sanity
${MSG} "Validating port with portlint"
PORTLINT_FLAGS="-abct"
if [ "${MODE}" = "new" ]
then
	PORTLINT_FLAGS="${PORTLINT_FLAGS} -N"
fi
portlint ${PORTLINT_FLAGS}
if [ $? -ne 0 ]
then
	${ERROR} "validating port"
	exit 1
fi

# Check to see the config file exists; generate one if not
if [ ! -f ${CONFIG} ]
then
	${MSG} "Generating ${CONFIG} configuration file"
	cat > ${CONFIG} <<- EOF
	# FreeBSD Port Tools configuration file
	# See pr-update(1)
	# vim: ft=sh
	EMAIL="${USER}@`hostname`"
	FULLNAME="`pw usershow -n ${USER} | cut -d: -f8`"
	ORGANIZATION=""
	BUILDROOT="/tmp"
	ARCHIVE_DIR=""
	DIFF_MODE="CVS"
	EOF
fi

# Reading configuration file
${MSG} "Reading configuration from ${CONFIG}"
. ${CONFIG}

# Collect information about the port
PORTNAME="`make -V PKGNAMEPREFIX``make -V PORTNAME``make -V PKGNAMESUFFIX`"
PORTVERSION="`make -V PORTVERSION`"
PKGNAME="`make -V PKGNAME`"
CATEGORY="`make -V CATEGORIES | sed -E 's/^([^ ]+).*$/\1/'`"
MAINTAINER="`make -V MAINTAINER`"
COMMENT="`make -V COMMENT`"

# Collect information about the local system
RELEASE="`uname -srp`"
SYSTEM="`uname -a | cut -d ' ' -f 1-12`"

# Notify the port maintainer
CC="${MAINTAINER}"

# Do not CC yourself or freebsd-ports list
if [ "${CC}" = "${EMAIL}" -o "${CC}" = "ports@FreeBSD.org" ]; then
	CC=""
fi

# Set some variables depending on run-mode
case ${MODE} in
new)
	# Submitting a new port
	NEW_PORT="yes"
	CLASS="change-request"
	PREFIX="NEW PORT"
	SUFFIX="${COMMENT}"
	DESCRIPTION=""
	CC=""
	;;
update)
	# Submitting an update to a newer version of an existing port
	CLASS="update"
	PREFIX="PATCH"
	SUFFIX="update to ${PORTVERSION}"
	DESCRIPTION="- Update to ${PORTVERSION}"
	;;
change)
	# Submitting a change to an existing port
	CLASS="change-request"
	PREFIX="PATCH"
	SUFFIX="[SUMMARIZE CHANGES]"
	DESCRIPTION="[DESCRIBE CHANGES]"
	;;
esac

# If you are the port maintainer, change prefix and PR class
if [ "${MODE}" != "new" -a "${MAINTAINER}" = "${EMAIL}" ]; then
	PREFIX="MAINTAINER"
	CLASS="maintainer-update"
fi

# Create a temporary dir for generated files (patch/shar, PR form)
TEMPROOT="`mktemp -d -t ${MODE}`" || exit 1

case ${MODE} in
new)
	${MSG} "Creating shar file"
	PATCH="${TEMPROOT}/${PKGNAME}.shar"
	SAVE_CWD="`pwd`"
	DIR="`basename ${SAVE_CWD}`"
	cd ..
	shar `find ${DIR}` > ${PATCH}
	if [ $? -ne 0 ]
	then
		${ERROR} "generating patch"
		rm -rf ${TEMPROOT}
		exit 1
	fi
	cd ${SAVE_CWD}
	;;
change|update)
	# Default to CVS diff mode
	[ "${DIFF_MODE}" = "" ] && DIFF_MODE="CVS"

	# If there is no CVS subdirectory then
	# fallback to diffing against /usr/ports tree 
	if [ "${DIFF_MODE}" = "CVS" -a ! -d CVS ]
	then
		DIFF_MODE="/usr/ports"
	fi

	if [ "${DIFF_MODE}" = "CVS" ]
	then
		# Test for ~/.cvspass and create if necessary
		test -f ${HOME}/.cvspass || touch ${HOME}/.cvspass

		# Run 'cvs update' first
		${MSG} "Updating from CVS"
		cvs update -Pd
		if [ $? -ne 0 ]
		then
			${ERROR} "updating CVS"
			rm -rf ${TEMPROOT}
			exit 1
		fi

		DIFF_CMD="cvs diff -u"
	else 
		# Non-CVS modes
		if [ -d ${DIFF_MODE} ]
		then
			# -d <dir> must have been specified
			# it should be Ports tree location
			ORIG_DIR="${DIFF_MODE}/${CATEGORY}/${PORTNAME}"
		else 
			# -d <pattern> must have been specified
			# <pattern> is used to determine original port location
			ORIG_DIR="`pwd`${DIFF_MODE}"
		fi

		# Check to see if the original version of port exist 
		if [ ! -d ${ORIG_DIR} ]
		then
			echo "Original version does not exist at ${ORIG_DIR}"
			rm -rf ${TEMPROOT}
			exit 1
		fi
		
		DIFF_CMD="diff -ruN --exclude=CVS ${ORIG_DIR} `pwd`"
	fi

	# Generate patch
	${MSG} "Generating patch"
	PATCH="${TEMPROOT}/${PKGNAME}.patch"
	${DIFF_CMD} > ${PATCH}
	#if [ $? -ne 0 ]
	#then
	#	${ERROR} "generating patch"
	#	exit 1
	#fi

	# Check to see if maintainership was requested
	MAINT_CHANGE="`grep '^[+-]MAINTAINER=' ${PATCH} | wc -l`"
	if [ ${MAINT_CHANGE} -eq 2 ]
	then
		CLASS="update"
		PREFIX="PATCH"
		SUFFIX="${SUFFIX}, take maintainership"
		DESCRIPTION="${DESCRIPTION}, take maintainership"
	fi
	;;
esac

# Generate Synopsis line
SYNOPSIS="[${PREFIX}] ${CATEGORY}/${PORTNAME}: ${SUFFIX}"

${MSG} "Generating PR form"
PR_FORM="${TEMPROOT}/PR"
cat > ${PR_FORM} << EOF
SEND-PR: -*- send-pr -*-
To: FreeBSD-gnats-submit@freebsd.org
From: ${FULLNAME} <${EMAIL}>
Cc: ${CC}
X-send-pr-version: 3.113
X-GNATS-Notify: 


>Submitter-Id:	current-users
>Originator:	${FULLNAME}
>Organization:	${ORGANIZATION}
>Confidential:	no 
>Synopsis:	${SYNOPSIS}
>Severity:	${SEVERITY}
SEND-PR: 	[ non-critical | serious | critical ] 
>Priority:	${PRIORITY}
SEND-PR: 	[ low | medium | high ]
>Category:	ports 
SEND-PR: <choose from the list of categories below (one line)>
SEND-PR: advocacy  alpha     bin       conf      docs      gnu       
SEND-PR: i386      ia64      java      kern      misc      ports     
SEND-PR: powerpc   sparc64   standards www       
>Class:		${CLASS}
SEND-PR: [ sw-bug | doc-bug | change-request | update | maintainer-update ]
>Release:	${RELEASE}
>Environment:
System: ${SYSTEM}
>Description:
EOF

case ${MODE} in
new)
	cat pkg-descr >> ${PR_FORM}
	;;
*)
	echo ${DESCRIPTION} >> ${PR_FORM}
	if [ "${CC}" != "" ]
	then
		echo >> ${PR_FORM}
		echo "Port maintainer (${MAINTAINER}) is cc'd." >> ${PR_FORM}
	fi
esac

cat >> ${PR_FORM} << EOF

Generated with FreeBSD Port Tools __VERSION__
>How-To-Repeat:
>Fix:
EOF

# Invoke send-pr(1)
${MSG} "Invoking send-pr to submit a PR"
PR_FORM="${PR_FORM}" /usr/bin/send-pr -a "${PATCH}"
if [ $? -ne 0 ]
then
	${ERROR} "submitting PR"
	rm -rf ${TEMPROOT} ${TMPDIR:-/tmp}/pbad.*
	exit 1
fi

# Cleanup
${MSG} "Saving submitted PR, cleaning up"
if [ -n "${ARCHIVE_DIR}" -a -d ${ARCHIVE_DIR} ]
then
	mv ${PATCH} ${ARCHIVE_DIR}
fi
rm -rf ${TEMPROOT}

${MSG} "Done"
exit 0
